[package]
name = "browser-top"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-cors = "0.6.4"
actix-files = "0.6.2"
actix-web = "4.3.1"
serde = "1.0.152"
serde_json = "1.0.94"
sysinfo = "0.28.2"
tokio = { version = "1.26.0", features = ["full"] }
